In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("Social_Media_Analysis.csv")
df.head()

,post_id,platform,content_type,topic,language,region,post_datetime,hashtags,sentiment_score,views,likes,comments,shares,engagement_rate,is_viral
0,1,LinkedIn,article,Technology,UR,BR,2025-04-25 09:47:00,#AI #Innovation #TechTrends #Programming #Codi...,0.76,37781,1202,462,185,0.0490,0
1,2,LinkedIn,poll,Health,FR,JP,2025-10-29 09:44:00,#Fitness #Nutrition #Wellness #Health #MentalH...,0.46,23541,1399,538,215,0.0915,1
2,3,LinkedIn,article,Travel,HI,FR,2025-02-10 14:12:00,#Travel #Journey #Adventure #Tourism #ExploreM...,-0.01,30714,1663,639,255,0.0833,1
3,4,LinkedIn,image,Sports,DE,DE,2025-04-18 22:41:00,#Cricket #Workout #Fitness,0.55,31294,1372,528,211,0.0675,0
4,5,LinkedIn,poll,Business,DE,US,2025-04-28 10:17:00,#Entrepreneur #Leadership #StartupLife,0.70,43129,2234,859,343,0.0797,0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   post_id          10000 non-null  int64
 1   platform         10000 non-null  object
 2   content_type     10000 non-null  object
 3   topic            10000 non-null  object
 4   language         10000 non-null  object
 5   region           10000 non-null  object
 6   post_datetime    10000 non-null  object
 7   hashtags         10000 non-null  object
 8   sentiment_score  10000 non-null  float64
 9   views            10000 non-null  int64
 10  likes            10000 non-null  int64
 11  comments         10000 non-null  int64
 12  shares           10000 non-null  int64
 13  engagement_rate  10000 non-null  float64
 14  is_viral         10000 non-null  int64
dtypes: float64(2), int64(6), object(7)
memory usage: 1.1+ MB

In [4]:
df.isnull().sum()

post_id            0
platform           0
content_type       0
topic              0
language           0
region             0
post_datetime      0
hashtags           0
sentiment_score    0
views              0
likes              0
comments           0
shares             0
engagement_rate    0
is_viral           0
dtype: int64

In [5]:
df["total_engagement"] = df["likes"] + df["comments"] + df["shares"]
df.head()

,post_id,platform,content_type,topic,language,region,post_datetime,hashtags,sentiment_score,views,likes,comments,shares,engagement_rate,is_viral,total_engagement
0,1,LinkedIn,article,Technology,UR,BR,2025-04-25 09:47:00,#AI #Innovation #TechTrends #Programming #Codi...,0.76,37781,1202,462,185,0.0490,0,1849
1,2,LinkedIn,poll,Health,FR,JP,2025-10-29 09:44:00,#Fitness #Nutrition #Wellness #Health #MentalH...,0.46,23541,1399,538,215,0.0915,1,2152
2,3,LinkedIn,article,Travel,HI,FR,2025-02-10 14:12:00,#Travel #Journey #Adventure #Tourism #ExploreM...,-0.01,30714,1663,639,255,0.0833,1,2557
3,4,LinkedIn,image,Sports,DE,DE,2025-04-18 22:41:00,#Cricket #Workout #Fitness,0.55,31294,1372,528,211,0.0675,0,2111
4,5,LinkedIn,poll,Business,DE,US,2025-04-28 10:17:00,#Entrepreneur #Leadership #StartupLife,0.70,43129,2234,859,343,0.0797,0,3436

In [6]:
df.groupby("platform")["total_engagement"].sum()

platform
Instagram     96614754
LinkedIn       5096630
Medium        16505141
YouTube      116191215
Name: total_engagement, dtype: int64

In [7]:
platform_rank = df.groupby("platform")["total_engagement"].sum().sort_values(ascending=False)
platform_rank

platform
YouTube      116191215
Instagram     96614754
Medium        16505141
LinkedIn       5096630
Name: total_engagement, dtype: int64

In [8]:
df.groupby("platform")["total_engagement"].mean().sort_values(ascending=False)

platform
YouTube      46476.4860
Instagram    38645.9016
Medium        6602.0564
LinkedIn      2038.6520
Name: total_engagement, dtype: float64

In [9]:
top_posts = df.sort_values("total_engagement", ascending=False).head(5)
top_posts

,post_id,platform,content_type,topic,language,region,post_datetime,hashtags,sentiment_score,views,likes,comments,shares,engagement_rate,is_viral,total_engagement
9740,9741,YouTube,video,Entertainment,EN,FR,2025-12-05 22:22:00,#Funny #FollowForMore #ShowBiz #MovieTime #Tre...,0.89,996835,116255,44713,17885,0.1794,1,178853
9307,9308,YouTube,video,Business,HI,FR,2025-04-18 19:49:00,#Entrepreneur #BusinessTips #Leadership #Caree...,0.86,968080,115995,44613,17845,0.1843,1,178453
8269,8270,YouTube,video,Entertainment,EN,MX,2025-02-25 21:39:00,#ShowBiz #Entertainment #Funny,0.77,995053,111911,43042,17217,0.1730,1,172170
8310,8311,YouTube,video,Lifestyle,ES,US,2025-06-16 20:19:00,#Motivation #Positivity #Lifestyle #Wellness,0.99,943937,110828,42626,17050,0.1806,1,170504
7631,7632,YouTube,video,Education,EN,DE,2025-11-30 10:14:00,#StudyTips #AcademicSuccess #Certification #Kn...,0.66,965391,110263,42409,16963,0.1757,1,169635

In [10]:
df["total_engagement"].describe()

count     10000.000000
mean      23440.774000
std       31461.595413
min           4.000000
25%        2496.000000
50%        8467.000000
75%       33026.000000
max      178853.000000
Name: total_engagement, dtype: float64

In [11]:
df[["likes", "comments", "shares", "total_engagement"]].corr()

                  likes  comments  shares  total_engagement
likes               1.0       1.0     1.0               1.0
comments            1.0       1.0     1.0               1.0
shares              1.0       1.0     1.0               1.0
total_engagement    1.0       1.0     1.0               1.0